name: Daily Shahnameh Post

on:
  schedule:
    - cron: "0 6 * * *"
    - cron: "0 14 * * *"
    - cron: "0 20 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  send-post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils
          pip install requests pdf2image

      - name: Send Shahnameh Pages
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python send_post.py

      - name: Update State
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add state.json
          git commit -m "Update last page" || echo "No changes to commit"
          git push
